name: LE-V-EL

description: >
  Provide standardized visualization benchmark datasets
  Rankings of computational methods for visualization understanding.

lang: en-US

# permalink: /:title/

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
