name: Remote SSH Command
on:
  push
#   pull_request:
#     types:
#       - closed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Check if script has already been executed
        id: check_execution
        run: |
          if [ -f /home/woodylin/published.lock ]; then
            echo "::set-output name=already_executed::true"
          else
            echo "::set-output name=already_executed::false"
          fi

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [ "${{ steps.check_execution.outputs.already_executed }}" = "false" ]; then
              /home/woodylin/publish.sh
              echo "$(date)" > /home/woodylin/published.lock
            else
              echo "Script already executed. Skipping script execution."
            fi
